### ISSUE TITLE
How to add a clear button to clear the entered text?

### ISSUE THREAD

**Issue by jkano** [koukibadr/Searchable-Listview#11]
Hi, 

I love your implementation of a searchable list view, my question is if you have a way to add a clear button that appears at the right of the search bar to clear the current entered text.

Thanks!

**Comment by koukibadr** [comment]
Hello @jkano thanks for your support,
Yes I think it will be a good feature to add to the package thanks for the idea, I will work on it

**Comment by koukibadr** [comment]
Hello again @jkano 
I just published a new version of the package contains the new feature (clear button in textfield) check it out 
[https://pub.dev/packages/searchable_listview](https://pub.dev/packages/searchable_listview)

**Comment by jkano** [comment]
Hi @koukibadr thanks for the quick reply and update on the package. 

I updated the package and I can confirm that the clear function works perfectly! 

As a suggestion, inside the _renderSuffixIcon function maybe you can add a parameter to disable the search icon that is displayed when there's no text and the textfield is focused so it will display the clear icon when there's text and no icon at all when there's no text.

Thanks!

**Comment by koukibadr** [comment]
Hello @jkano 
Okay I will add a new parameter to the package to add this behaviour
Thanks for  your support
