### ISSUE TITLE
Keyboard Closing

### ISSUE THREAD

**Issue by dadey09** [koukibadr/Searchable-Listview#48]
after 1 character the keyboard close and textfield lost focus

**Comment by koukibadr** [comment]
hello @dadey09 can you please provide more details about this issue ?

**Comment by dadey09** [comment]
Yes. I the same code from pub.dev, and trying to type on the field to search. After pressing the first character either by laptop keyboard or through emulator, keypad automatically closes down. Only happens on the first time using the search. File Video attached

https://user-images.githubusercontent.com/88657903/201647558-a0618d4f-9209-4b24-817e-4d061944b9f8.mp4

**Comment by danieljiwonkang98** [comment]
I am having the same issue

**Comment by koukibadr** [comment]
Helllo @dadey09  @danieljiwonkang98  I will publish a new version of the package fixing this bug thanks for your feedback

**Comment by danieljiwonkang98** [comment]
@koukibadr Any updates?

**Comment by danieljiwonkang98** [comment]
@koukibadr Is this bug being fixed?

**Comment by koukibadr** [comment]
hello @danieljiwonkang98 sorry for not responding to you to your last message.
A new version will be published this thursday fixing the bug

**Comment by danieljiwonkang98** [comment]
Thank you!

**Comment by danieljiwonkang98** [comment]
@koukibadr Where can I find the fix?

**Comment by koukibadr** [comment]
Hello @danieljiwonkang98 sorry for the late response 
a new version has been published to fix this bug 
now you can parameter the focus on the textfield it's by default true so the search field will have the focus on it 
[https://pub.dev/packages/searchable_listview](https://pub.dev/packages/searchable_listview)

**Comment by danieljiwonkang98** [comment]
@koukibadr Thank you so much!

**Comment by danieljiwonkang98** [comment]
@koukibadr I found a bug. If you use another language aside from english, after typing in the first character (in another language (I was using korean)) the focusnode loses focus. Can you look over this issue? Thank you.

**Comment by koukibadr** [comment]
okay @danieljiwonkang98 I will check it out

**Comment by tibfox** [comment]
Good that this is still open because the setting *autoFocusOnSearch* does not solve this issue.

The introduced setting will force the focus immediatly when building the widget tree happened. I want the user to actively decide to search and not force him just so the text input doesn't lose focus after the first character. My search field is somewhere in the middle of the page.

Please fix this bug so I can actually use this handy package! :) @koukibadr

**Comment by koukibadr** [comment]
@tibfox thanks for the feedback
I'll let you know when a new version get published it will be this week

**Comment by hld0** [comment]
The problem still persists. A workaround is to use `SEARCH_TYPE.onSubmit` for now, but I'd love to use `onEdit` .

Unfortunately I don't really understand why it dismisses the keyboard only after the first time filtering the results. After that it is working perfectly.

**Comment by koukibadr** [comment]
@hld0 I'll try the solution you mentioned above the fix of this issue will be available in the next version

**Comment by hld0** [comment]
Nice! Just tell me if you need any more details or if I can otherwise help. 
Thanks for your work!

**Comment by koukibadr** [comment]
This issue has been resolved in the newest version 2.10.2 
check it out and let me know all your feedback [https://pub.dev/packages/searchable_listview](https://pub.dev/packages/searchable_listview)

feel free to close this issue

**Comment by hld0** [comment]
Hi! I just tested it and it works like a charm! 

Great work, thank you :)
