### ISSUE TITLE
Builder index not offset for filter - cannot get correct object

### ISSUE THREAD

**Issue by idraper** [koukibadr/Searchable-Listview#66]
When using the builder function which now returns the index, when the items are filtered it returns the index of the object in the filtered list. This functionality makes sense (and is how I use the index in other areas of the code). However, this means if you try to use this index to get the object you cannot.

See the following example:

```
class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final listObjects = [1,2,3,4];

  return SearchableList.seperated(
      shrinkWrap: true,
      initialList: listObjects,
      filter: (value) => listObjects
          .where((myNum) => value.isEmpty || myNum == int.tryParse(value))
          .toList(),
      inputDecoration: InputDecoration(
        labelText: 'Search',
      ),
      seperatorBuilder: (context, index) => const Divider(
        color: Colors.black54,
        height: 1,
        thickness: 1,
      ),
      builder: (index) {
        final myNum = listObjects[index];
        return Center(child: Text('$myNum'));
      },
    );
  }
}
```

Here are some screenshots of using the above:
![0](https://github.com/koukibadr/Searchable-Listview/assets/32877813/c6ce5093-32bc-44c2-9e50-5771da18bd7b)
![1](https://github.com/koukibadr/Searchable-Listview/assets/32877813/2a66a63b-38f0-4f3a-b045-14daf337995d)
![3](https://github.com/koukibadr/Searchable-Listview/assets/32877813/39e26ffe-feff-447b-83fc-14a3dcbcf960)
![4](https://github.com/koukibadr/Searchable-Listview/assets/32877813/949b5a72-567c-42e3-9971-dfdadb4a4635)
![5](https://github.com/koukibadr/Searchable-Listview/assets/32877813/eb19ee26-7088-40a9-b546-9617702280a3)

As you can see - no matter the filter, the index is always 0 (because 1 item is returned) and when trying to get the object from the list, this is always the first element.

I think the simplest solution is to simply include the object in the callback. Alternatively, you could include the original index. Either:
```
 builder: (obj, index) {
  final myNum = obj;
  return Center(child: Text('$myNum'));
},
```
or
```
 builder: (index, unfilteredIndex) {
  final myNum = listObjects[unfilteredIndex];
  return Center(child: Text('$myNum'));
},
```

However, I wouldn't remove the functionality of `index` as it is, since it is useful to know the actual index of the filtered objects. In my specific case, I still use it to alternate background colors of each object (using `index % 2 ...`).

**Comment by GaoWhitebird** [comment]
It is the same for me. Is there any solution ?

**Comment by WMOH-DEV** [comment]
same issue here 
filter doesn't work 
i don't know why they updated it to be by index not the model !!!!

**Comment by koukibadr** [comment]
@idraper @GaoWhitebird @WMOH-DEV thanks for your feedback 
a new version has been published fixing this issue
feel free to close the issue if everything is OK 
[https://pub.dev/packages/searchable_listview](https://pub.dev/packages/searchable_listview)

**Comment by idraper** [comment]
@koukibadr that fixes the issue of getting the right object, but it is now not possible to know the index of the actual list (both are useful/needed for different scenarios). Specifically, in my case, I alternate colors to make each item show they are separate which needs the index of the filtered objects. Both indices are needed.

**Comment by koukibadr** [comment]
@idraper I will update the wiget builder attribute, a new version will be uploaded by the end of the week

**Comment by koukibadr** [comment]
@idraper a new version has been published, this new update expose two integers in the builder parameter the first is the initial index of the item and the second one is the actual index (after applying filter) 
[https://pub.dev/packages/searchable_listview](https://pub.dev/packages/searchable_listview)
feel free to close this issue if everyting is okay, happy to receive your issues

**Comment by koukibadr** [comment]
Check out the newest Searchable listview version fixing this bug and many other updates
[https://pub.dev/packages/searchable_listview](https://pub.dev/packages/searchable_listview)

**Comment by idraper** [comment]
Sorry for the delayed response - these changes look great! All issues are fixed, thanks for the speedy support.

**Comment by koukibadr** [comment]
Thanks for your support @idraper
