### ISSUE TITLE
Would you pls create a new function to support two or more keys for filter data?

### ISSUE THREAD

**Issue by 13692277450** [koukibadr/Searchable-Listview#7]
Hi koukibadr,

Many thanks for your plugin and I used it in my Flutter App, it's very good plugin to help me. but I hava a suggestion to you, because my search results need filter data from two keys value, but your plugin only support one key value,  any possible to extend your plugin function to include more keys value for filter data? my desired list as below:

current version:
========================
 List<Actor> _filterUserList(search) {
    return actors
        .where(
          (element) => element.function.contains(search),
          // (element) => element.Name.toLowerCase().contains(search),
        )
        .toList();
  }
===========================

my desired version:

===========================

 List<Actor> _filterUserList(search) {
    return actors
        .where(
          (element) => element.function.contains(search) or element.Name.contains(search),
        )
        .toList();
  }

===========================

my homepage is: www.pavogroup.top and welcome you to visit!

many thanks for your support and looking forward to see your reply.

Have a nice day！
Mang Zhang/China.

**Comment by koukibadr** [comment]
@13692277450 sorry for the late response okay I will work on it and it will be available in the next version

**Comment by koukibadr** [comment]
thanks @13692277450 for your support and your feedback 
for the issue actually you can create filter with many attributes that you need 
the example I wrote is simple one but also I can filter my actors list with other attributes
example: 

```dart
List<Actor> _filterUserList(search) {
    return actors
        .where(
          (element) =>
              element.name.toLowerCase().contains(search) ||
              element.lastName.contains(search),
        )
        .toList();
  }
```
the widget searchableList accept a callback with String parameter in the function you can filter the way you want
