### ISSUE TITLE
Cant manipulate search from outer values

### ISSUE THREAD

**Issue by cenkingunlugu** [koukibadr/Searchable-Listview#87]
Lets say i have predefined filters, on the emptywidget, i am showing them, and as i am able to set texteditingcontroller, i can set the text when user clicks my predefined filters.

The problem is, even though the text changes, search does not start.

But if i change a letter with the keyboard, search continues.

Long story short, when i set value without the keyboard, search does not trigger.

**Comment by koukibadr** [comment]
@cenkingunlugu I'll verify this issue

**Comment by koukibadr** [comment]
@cenkingunlugu a new version has been published fixing this issue check it out
feel free to close this issue once everything is okay
