### ISSUE TITLE
`LateInitializationError: Field 'sortWidget' has not been initialized.`

### ISSUE THREAD

**Issue by hld0** [koukibadr/Searchable-Listview#89]
Hi!

When trying out the example with a sliver search bar from the README

```dart
SearchableList<Actor>.sliver(
      initialList: actors,
      filter: (query) {
        return actors.where((element) => element.name.contains(query)).toList();
      },
      builder: (list, index, item) {
        return ActorItem(actor: list[index]);
      },
    );
```

I get the following error

```
The following LateError was thrown building SearchableList<Actor>(dirty, state: _SearchableListState<Actor>#bbf5a):
LateInitializationError: Field 'sortWidget' has not been initialized.


When the exception was thrown, this was the stack: 
#0      SearchableList.sortWidget (package:searchable_listview/searchable_listview.dart)
#1      _SearchableListState.renderSliverEffect (package:searchable_listview/searchable_listview.dart:882:44)
#2      _SearchableListState.build (package:searchable_listview/searchable_listview.dart:462:15)
...
```

I spent a bit of time to understand the error but I could not get to the bottom of it unfortunately. It seems as if it somewhere expects the `sortWidget` although for the sliver the parameter `displaySortWidget` is `false` by default.

The other constructors work without an issue.

**Comment by koukibadr** [comment]
@hld0 a new version has been published fixing this issue check it out
feel free to close this issue once everything is okay

**Comment by hld0** [comment]
The error seems to be resolved! I have now moved away from the sliver list and I am using the async list instead. The only thing I have noticed is that there is a "Back" icon (left chevron) which is overlaying the search text box when using `SearchableList.sliver`.

But I would need to investigate this further, and I will open another issue if this remains.

Thank you again!
